### ISSUE TITLE
Document how to work with dbus services

### ISSUE THREAD

**Issue by sharpenedblade** [zbentley/dbus-osx-examples#3]
I want to run fractal on macos, and have gnome-keyring installed. This calls dbus-launch --autolaunch, which fails on macos. There is no documentation on how to start dbus services

**Comment by zbentley** [comment]
After following the instructions in https://github.com/zbentley/dbus-osx-examples/tree/master/installation, running a service should only require starting that service's executable, after which it'll connect to whichever bus and handle events.

`dbus-launch` is a (likely not working on MacOS, or not working with default settings) means of running a session bus dbus instance. There are instructions for how to do that manually in the above link. Does Fractal unconditionally call `dbus-launch`, or does it only do so if it cannot fund a running session bus to connect to?

**Comment by sharpenedblade** [comment]
I think it uses GDbus, which always does that, but there was a commit last week that made it work on macos without anything extra, is it was already started by launchd.

**Comment by zbentley** [comment]
Good to know! So is this issue resolved, or should the documentation in this repo be updated somehow?

**Comment by sharpenedblade** [comment]
I think the repo should mention that dbus services need to be started, and that a launchd dbus must be running.
